"""Reporting: JSON, CSV, self-contained HTML."""
from __future__ import annotations

import csv
import html
import json
import os
from datetime import datetime, timezone


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def save_json(results: list[dict], path: str) -> str:
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"generated_at": _stamp(), "count": len(results),
                   "results": results}, f, indent=2, default=str)
    return path


def save_csv(results: list[dict], path: str) -> str:
    fields = ["domain", "technique", "registered", "score", "verdict",
              "distance", "entropy", "risk_reasons", "registered_reasons"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in results:
            w.writerow({k: ("; ".join(map(str, r.get(k, [])))
                            if isinstance(r.get(k), list) else r.get(k, ""))
                        for k in fields})
    return path


HTML_TMPL = """<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>PhishDec report — {legit}</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body{{font-family:system-ui,Arial,sans-serif;background:#0b1220;color:#e6edf3;margin:0}}
header{{padding:20px 28px;background:#111c33;border-bottom:1px solid #223}}
.badges span{{display:inline-block;margin:4px 8px 0 0;padding:4px 10px;border-radius:20px;font-size:13px}}
.CRITICAL{{background:#7f1d1d}}.HIGH{{background:#b45309}}.MEDIUM{{background:#854d0e}}
.LOW{{background:#14532d}}.CLEAR{{background:#1f2937}}
main{{padding:20px 28px}}input{{width:100%;padding:10px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#fff;margin:10px 0}}
table{{width:100%;border-collapse:collapse;font-size:14px}}th,td{{text-align:left;padding:8px;border-bottom:1px solid #1f2937;vertical-align:top}}
th{{position:sticky;top:0;background:#111c33}}tr.reg{{background:rgba(185,28,28,.12)}}
.small{{color:#94a3b8;font-size:12px}}</style></head><body>
<header><h1>PhishDec report</h1>
<div>Target: <b>{legit}</b> &nbsp;·&nbsp; Variants: <b>{count}</b> &nbsp;·&nbsp; Registered: <b>{nreg}</b> &nbsp;·&nbsp; {ts}</div>
<div class="badges">{badges}</div></header>
<main><input id="q" placeholder="Filter domains, techniques, verdicts…" oninput="f()">
<table><thead><tr><th>Domain</th><th>Technique</th><th>Reg?</th><th>Score</th><th>Verdict</th><th>Why</th></tr></thead>
<tbody id="rows">{rows}</tbody></table>
<p class="small">Generated by PhishDec. DNS/WHOIS/CT evidence in JSON export.</p></main>
<script>function f(){{var q=document.getElementById('q').value.toLowerCase();
document.querySelectorAll('#rows tr').forEach(function(r){{r.style.display=r.innerText.toLowerCase().includes(q)?'':'none'}})}}</script>
</body></html>"""


def save_html(results: list[dict], path: str, legit: str = "") -> str:
    from collections import Counter
    counts = Counter(r.get("verdict", "?") for r in results)
    badges = "".join(f'<span class="{html.escape(k)}">{html.escape(k)}: {v}</span>'
                     for k, v in counts.most_common())
    rows = []
    for r in results:
        why = "; ".join(r.get("risk_reasons", []) + r.get("reasons_reg", []))
        rows.append(
            f'<tr class="{"reg" if r.get("registered") else ""}">'
            f'<td><b>{html.escape(r.get("domain", ""))}</b></td>'
            f'<td>{html.escape(r.get("technique", ""))}</td>'
            f'<td>{"YES" if r.get("registered") else "no"}</td>'
            f'<td>{r.get("score", 0)}</td>'
            f'<td><span class="{html.escape(r.get("verdict", ""))} badges">'
            f'<span class="{html.escape(r.get("verdict", ""))}">{html.escape(r.get("verdict", ""))}</span></span></td>'
            f'<td class="small">{html.escape(why[:400])}</td></tr>')
    with open(path, "w", encoding="utf-8") as f:
        f.write(HTML_TMPL.format(legit=html.escape(legit), count=len(results),
                                 nreg=sum(1 for r in results if r.get("registered")),
                                 ts=html.escape(_stamp()), badges=badges,
                                 rows="\n".join(rows)))
    return path


def save_report(results: list[dict], basename: str = "phishdec_report",
                formats: tuple = ("json", "html", "csv"),
                legit: str = "") -> list[str]:
    out = []
    base, _ = os.path.splitext(basename)
    if "json" in formats:
        out.append(save_json(results, base + ".json"))
    if "csv" in formats:
        out.append(save_csv(results, base + ".csv"))
    if "html" in formats:
        out.append(save_html(results, base + ".html", legit=legit))
    return out
